### ISSUE TITLE
Constant looping of `connected` event when using SSL

### ISSUE THREAD

**Issue by dgsan** [rails/actioncable#101]
I've been trying to get websockets to work with SSL -- I've got them working fine without it in dev mode in both Puma and Thin without SSl, but adding it seems to make things go crazy: once SSL's in the picture I get infinite `connected` events.

I've tried with Thin and Puma, and with Nginx reverse proxying both.
 
Puma chokes on SSL: for some reason I get `Rack app error: #<TypeError: no implicit conversion of Puma::MiniSSL::Socket into Integer>` on each request with Puma. This doesn't happen with Thin, or reverse proxying to Puma.

However, each setup I've tried that doesn't have a bug like that (IE Thin, Nginx reverse proxy to Puma/Thin,  using `Faye::WebSocket.load_adapter('thin')` if needed, etc.) leads to a constant stream of Connected events (about 1 per second).

I'll see something along the lines of:
```
CandidateResearcherChannel#sub({"sub_id"=>120})
CandidateResearcherChannel transmitting {"current"=>[{"id"=>1, "name"=>"Dave", "application_id"=>120}], "type"=>"candidate_researcher"}
CandidateResearcherChannel is transmitting the subscription confirmation
CandidateResearcherChannel is streaming from researcher:application:120
```
repeated hundreds of times on the server console when using SSL. 

When using `ws://` with the same setup in dev instead of `wss://` from production/staging I'll see the same thing once in the server console.

On the client side JS console, this shows up as a new `connected` event at a rate of around 1 per second with `wss://` but likewise only shows up once with `ws://`.

My client code looks like:
```javascript
(function(){
    InterviewApp = InterviewApp || {};
    $(document).ready(function(){
        InterviewApp.cable = Cable.createConsumer(Rails.configuration.actioncable.websocket_address); // Address set elsewhere.
        InterviewApp.candidateResearcherChannel =  InterviewApp.cable.subscriptions.create('CandidateResearcherChannel', {
            received: function(data) {
                // Stuff happens here, doesn't really matter for the example and would take much space.
            },
            connected: function() {
                console.log("CONNECTED");
                var scope = this;
                setTimeout(function() {
                     console.log('CONNECTED callback...');
                     scope.perform('sub', {sub_id: InterviewApp.application_id});
                }, 1000);
            }
         });
     });
})();
```
It's mostly straight from examples I've seen.
Have a feeling I must be overlooking something, but not sure what.

**Comment by javan** [comment]
What rev are you running? @lifo fixed a similar sounding issue yesterday https://github.com/rails/actioncable/commit/506d84c157b041208f40b7034cac9c5d5e66fff5. If you're not already, can you try pointing to the latest commit and see if the issue persists?

**Comment by dgsan** [comment]
I'm on 904b83b, which includes 506d84c.
