### ISSUE TITLE
Recommended way to run ActionCable: Standalone or in-server

### ISSUE THREAD

**Issue by kayakyakr** [rails/actioncable#103]
I was about to do another round of improving the README with some things that I've found, but I was wondering if it's time for the recommended way to run ActionCable should change.

Currently, it works both in-app and stand-alone with any server that supports threading (thin, puma, etc). In-app is easier to get started on and easier to deploy since, as long as you have a rails server running, you also have a cable server running. Stand-alone gives you the advantage of independent scaling, so you can pick the number and size of servers more easily.

I'm partial to promoting in-app as the default strategy. It's so much easier to get started with, "just works" on heroku and most other deploys, for that matter, and being able to write the generators for this strategy specifically would be a great benefit. Still requires that you restart the server if you've made changes in channels, but that can't be helped.

**Comment by dhh** [comment]
I think it's fine to promote in-app as the default to get started, but also
say that large deployments in the wild, like Basecamp 3, use the
stand-alone model.

**Comment by kayakyakr** [comment]
Yeah, that's what I was thinking. Once you have to start thinking about scaling, it's time to switch over to stand-alone.

The nice thing is that it's very easy to change from one to the other. Set up new servers, set a load balanced location to point to the new cable server(s), remove the route from routes.rb.

**Comment by kaspth** [comment]
Sounds good, we should probably have instructions for moving from in app to stand alone setup too then :)
