### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error

### ISSUE THREAD

**Issue by huetsch** [rails/actioncable#104]
After running "bundle exec puma -p 28080  cable/config.ru" for a while, it always dies with the following error:

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: adding existing descriptor
Abort trap: 6

I believe it may be related to this faye-websocket-ruby bug:

https://github.com/faye/faye-websocket-ruby/issues/35

The server randomly dying all the time is a pretty big issue for using actioncable smoothly in production.

**Comment by nflorentin** [comment]
+1
I'm facing the same issue and a bit worried about putting this into production

**Comment by mikecarroll** [comment]
+1

**Comment by dhh** [comment]
Odd. We've not seen any of these issues in production. At least that I'm aware of! And we have many tens of thousands of daily active users on Basecamp 3.

**Comment by mikecarroll** [comment]
It seems to be happening to us only when running locally, not in production. Our servers are Linux but we use OSX for dev, so maybe it's an OSX issue?

**Comment by nflorentin** [comment]
We are exactly in the same situation described by @mikecarroll, Linux servers in prod and OS X for dev.

**Comment by dhh** [comment]
Maybe we can just start by saying this is a problem on OSX in the readme for now? Don't think anyone is actually deploying on OSX. I don't know if this is really something we can solve in AC anyway?

**Comment by rafaelfranca** [comment]
This issue was moved to rails/rails#22676
