### ISSUE TITLE
[Suggestion] Cable Dashboard Gem

### ISSUE THREAD

**Issue by wazery** [rails/actioncable#105]
I am proposing to create a new gem to act as a dashboard for the Cable server. So it can list all the events as they got sent, what's going on the Cable server, and creating new events from it, something much like Pusher's dashboard:

![Pusher's dashboard ](http://www.internet-of-things-book.com/style/images/pusher4.jpg)

WDYT guys/gals, can I proceed to work on it?

**Comment by seuros** [comment]
I like it. We can pair of it if you want.

**Comment by wazery** [comment]
@seuros That would be awesome :smiley:. I will email you with my contact details.

**Comment by seuros** [comment]
:smiley_cat:  Dude, we already in each other contact list :).

**Comment by kaspth** [comment]
Sounds cool 👍

Also you don't need our permission to write a separate gem, as Action Cable has an MIT license. So have at it 😁

**Comment by wazery** [comment]
Yea, sure it's not a permission, it's more like checking the idea and if more people interested.

**Comment by kaspth** [comment]
Ah sure, I misunderstood the intent 😁

**Comment by mklemme** [comment]
Can you post a link to the repo once you start, @wazery?
