### ISSUE TITLE
Must use ActiveSupport::TaggedLogging otherwise TaggedLoggerProxy will throw errors 

### ISSUE THREAD

**Issue by daino3** [rails/actioncable#107]
I don't know if this is a better documentation thing or not, but we weren't using ActiveSupport loggers in our demo environment and kept getting `undefined method 'current_tags' for nil` and when setting a formatter `undefined method 'current_tags' for #<Logger::Formatter123#>`

So, I guess the question is - is Action Cable so tightly coupled to ActiveSupport::TaggedLogging that it must always be configured to use it and not grab it from the rails config? Or should the documentation just touch on not overriding the Logger?

**Comment by rafaelfranca** [comment]
Have you checked it after https://github.com/rails/actioncable/pull/84 was merged?

**Comment by daino3** [comment]
Dangit! Laziness on my end for not going through the closed PRs and just looking at the issues. I must have pulled down literally the day before this was merged. In any event, I can confirm #84 does fix this issue for me. Thanks @rafaelfranca for the speedy followup.
