### ISSUE TITLE
can't connect to websocket

### ISSUE THREAD

**Issue by Electrofenster** [rails/actioncable#108]
I can't connect to the actioncable websocket.

I added this line to my routes.rb
```ruby
match "/websocket", :to => ActionCable.server, via: [:get, :post]
```
and I added this files to my app path:

cable/config.ru
```ruby
# cable/config.ru
require ::File.expand_path('../../config/environment',  __FILE__)
Rails.application.eager_load!

require 'action_cable/process/logging'

run ActionCable.server
```

channels/application_cable/channel.rb
```ruby
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end
```

channels/application_cable/connection.rb
```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    protected
      def find_verified_user
        if current_user
          current_user
        else
          reject_unauthorized_connection
        end
      end
  end
end
```

and my javascriptfiles under assets/javascript/channels/index.coffee
```coffee
#= require cable
#= require_self
#= require_tree .

@App = {}
# I tried both but it doesn't work
# App.cable = Cable.createConsumer 'ws://localhost:28080'
# App.cable = Cable.createConsumer 'ws://localhost/websocket'
```

then I started my rails app with puma:
````bash
TRUSTED_IP=192.168.0.0/16 rails s -b 192.168.56.101 Puma
```

and my ActionCalbe-Server with:
```bash
bundle exec puma -p 28080 cable/config.ru
```

When I opened my application in the browser I get this errors:
```
Firefox kann keine Verbindung zu dem Server unter ws://localhost:28080/ aufbauen.
Firefox kann keine Verbindung zu dem Server unter ws://localhost/websocket aufbauen.
```

What's wrong with my settings?

**Comment by vadimskrotsky** [comment]
if you use in app server, you don't need a separate server https://github.com/rails/actioncable#in-app

and you need to specify `action_cable.allowed_request_origins` in `config/application.rb`

for example:
```ruby
module App
  class Application < Rails::Application
    # ...

    # ActionCable
    config.action_cable.allowed_request_origins = %w( http://localhost:9292 )

    # ...
  end
end
```

**Comment by Electrofenster** [comment]
Okay thanks,
When I start my rails application with
```bash
TRUSTED_IP=192.168.0.0/16 rails s -b 192.168.56.101 Puma
```
the actioncable server starts with it?

**Comment by kayakyakr** [comment]
For the in-app, yes. I'll make that more clear with the next round of README updates.

Of note: your find authorized user function is not actually loading the user at all and may, in fact, be causing any connection to your cable server to reject. Until you get a connection working, I'd comment out `reject_unauthorized_connection`

**Comment by vadimskrotsky** [comment]
yes and you don't need `cable/config.ru` and `bundle exec puma -p 28080 cable/config.ru`
and may be in JavaScript:
```js
App.cable = Cable.createConsumer('ws://' + window.location.host + '/websocket');
```

**Comment by Electrofenster** [comment]
ok, thanks :+1: 
I'll test it later and give some feedback.
