### ISSUE TITLE
InvalidIdentifiersError Exception when use more than one identifier.

### ISSUE THREAD

**Issue by nateless** [rails/actioncable#109]
`Connection` class has `identified_by :current_user, :unique_id`, when somewhere later I call

`ActionCable.server.remote_connections.where(current_user: find_verified_user).disconnect` 

it throws an exception:
```
There was an exception - ActionCable::RemoteConnections::RemoteConnection::InvalidIdentifiersError(ActionCable::RemoteConnections::RemoteConnection::InvalidIdentifiersError)
```

Exception is being thrown [here](https://github.com/rails/actioncable/blob/master/lib/action_cable/remote_connections.rb#L60), because I did search only with one indetfier but not all, I suppose we need to change `all?` to `any?`

**Comment by dballona** [comment]
@nateless, is this happening because you're not passing a unique_id to `where` clause as well? I think `#valid_identifiers?` assumes that all keys should be passed.

**Comment by nateless** [comment]
@dballona, I've checked source for `identified_by ` [identification.rb#L19](https://github.com/rails/actioncable/blob/master/lib/action_cable/connection/identification.rb#L19) and it accepts array. So I thought I can use several identifiers to somehow "tag" connections.

**Comment by dballona** [comment]
Yup... it accepts multiple identifiers, but what I'm suggesting is that it probably is looking for an argument that passes all the arguments you've set in `identified_by` to find your remote connection.

Something in these lines:
```ruby
ActionCable.server.remote_connections.where(current_user: find_verified_user, unique_id: something_else).disconnect
```

But that's just a guess, based on code on `remote_connections.rb` :)

**Comment by nateless** [comment]
Yeah, I get it, but makes me feel kind wrong, why would you allow accept many identifiers if later you should combine them all and use as uniq? In that case you can make it in the identifier method.

**Comment by dballona** [comment]
I can think of a scenario which we have a multi-tenant application with a shared user base.
let's say we have an `Account` which has and belongs to many `User`.

You could be able of retrieve in which account that specific user would be doing an operation, by having `account_id` and `user_id` as identifiers.

But yeah, we can achieve the same result by just combining them, as you've said.

May I open a PR changing `.all?` to `.any?` so we can gather team's opinion? Or do you want to do it yourself?

**Comment by nateless** [comment]
Yeah, I was thinking the same scenario and it's just much easier to process it in the app identifier than pass it to AC. However with `.any?` there's a problem. 

Currently AC thinks and behaves as theres one and uniq identifier, when we will use it as some 'tag' method then where will `internal_redis_channel ` broadcast with `.any?` call?

**Comment by dballona** [comment]
Just by swapping to `.any?`, in every channel that contains one of the identifiers as a subscription, I guess. I'm not sure this is desired behavior, though.

I think we can get decisive feedback by just opening the PR and checking if it's desirable to make ActionCable behave like that.

**Comment by dballona** [comment]
@jeremy any thoughts? :)

**Comment by dhh** [comment]
Would be good to change this such that you can kill a connection based on any of the identifiers, BUT it still has to be possible to narrow the field down by including multiple identifiers. So where(user_id: x) should get all connections with user_id: x, but where(user_id: x:, connection_token: y) should only get the ones where both are true. Please do open a PR for this change with tests proving all the cases!
