### ISSUE TITLE
Add ActionCable as a topic to the guide

### ISSUE THREAD

**Issue by rafaelfranca** [rails/actioncable#114]
_From @openscript on November 4, 2015 10:21_

The release of Rails 5 is coming closer and closer. I've been spending some time with ActionCable, but I think there are still a few things to discover. Howsoever, I thought I can contribute something to the guides. So let's start the ActionCable topic.

---
Here is my idea about the chapter structure, based on Active Job Basics and Action Mailer Basics:
- [ ] Introduction: A few lines about what's ActionCable
- [ ] Technical background: How does ActionCable work? What's the PubSub pattern?
- [ ] Configuration of the service
- [ ] Creating a Cable
  - [ ] At the server-side
  - [ ] At the browser-side
- [ ] Opening a channel
  - [ ] At the server-side
  - [ ] At the browser-side
- [ ] Running the service

---
What do you think about? Is someone else working on this? 

_Copied from original issue: rails/rails#22178_

**Comment by rafaelfranca** [comment]
Lets move this discussion for Action Cable repository so you can start to work closer to the code.

**Comment by openscript** [comment]
Thanks! I started in the rails repository, because the guides are in that repository, too. So I thought it's the right place.

**Comment by dballona** [comment]
Has anyone started writing this up? I can take care of some topics such as:
- What's the PubSub pattern?
- Creating a cable;
- Opening a channel;

**Comment by kayakyakr** [comment]
Should the ActionCable README reflect the content of the guide?

**Comment by vasspilka** [comment]
Hey, I was thinking about contributing to documentation too, @openscript are you still interested into writing this?

**Comment by dhh** [comment]
Whoever wants to start work on this, that'd be great. We definitely need a guide!

**Comment by vasspilka** [comment]
I am now working on a rails 5 api that includes websockets through actioncable, but I can't say I am much experienced so I am not sure I am suitable to start a guide on my own.

I certainly could review and extend a guide.

**Comment by dhh** [comment]
Vasilis, we need some help combining the --api setup with Action Cable
generators. ACa generators should not produce the client-side code, like
app/assets/javascript/channels, when in --api mode. Could use some help
with that :D

**Comment by vasspilka** [comment]
How could I help? What I did was `rake assets:precompile` on a non --api setup and then copy the static asset to `/public/js/cable.js` and made static assets available, this way I was able to access the js as an external library in the client side.

**Comment by RochesterinNYC** [comment]
Is there a checklist or Trello board or something somewhere that lists out which topics still need documentation? I'd love to contribute some.

**Comment by davidkuhta** [comment]
I'm not sure if anyone began working on this, but I thought I'd share what I started: [action_cable_overview.md](https://github.com/davidkuhta/rails/blob/patch-1/guides/source/action_cable_overview.md).
Note: It does draws heavily from the README and code comments (as they were the guide I worked through to get started), but I restructured them in some areas. Let me know if it'd be a good starting point, but if nothing else, I'll be adding to it as I keep digging into AC.

**Outline:**

__Action Cable Overview__

1. Introduction
2. What is Pub/Sub?
3. What is Action Cable?
4. Server-Side Components
    1. Connections
        1. Connection Setup
    2. Channels
        1. Parent Channel Setup
        2. Subscriptions
5. Client-Side Components
    1. Connections
        1. Connect Consumer
    2. Subscriber
6. Client-Server Interaction
    1. Streams
    2. Broadcastings
    3. Subscriptions
    4. Pass Parameters to Channel
    5. Rebroadcasting message
7. Full Stack Examples
    1. Common Steps
    2. Example 1: User Appearances
        1. Create the Server-Side Appearance Channel
        2. Create the Client-Side Appearance Channel Subscription
    3. Example 2: Receiving New Web Notifications
        1. Create the Server-Side Web Notifications Channel
        2. Create the Client-Side Web Notifications Channel Subscription
        3. Broadcast content to a web notification channel instance from elsewhere in your application
    4. More complete examples
8. Configuration
    1. Redis Connection 
    2. Allowed Request Origins
    3. Other configurations
9. Running the cable server
    1. Standalone
    2. In app
 3. Notes
10. Dependencies
11. Deployment

**Comment by vasspilka** [comment]
@davidkuhta Thats great :) I will review it tomorrow it's getting kinda late here.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/rails#22673
