### ISSUE TITLE
Truncate log message

### ISSUE THREAD

**Issue by jnstq** [rails/actioncable#119]
I have just implemented ActionCable in our app. It feels great! I'm sending large json blocks, are there some way to truncate the logged message? I have tried to override the new_tagged_loggor but that does not affect the Broadcasting to log entry.

I can change the log level but then it feels to quite.

**Comment by lsylvester** [comment]
Current broadcasting line is `server.logger.info "[ActionCable] Broadcasting to #{broadcasting}: #{message}"`

Maybe it would be good to break it into two parts - with the Broadcasting To as info level, and the actual message as a debug level?

**Comment by jnstq** [comment]
That would be perfect. Should I create a pull request?

**Comment by dhh** [comment]
Happy to see a PR for some truncation, but it shouldn't be very aggressive. Only to catch truly huge JSONs.
