### ISSUE TITLE
Integration testing Cucumber / Phantomjs / Capybara / actioncable

### ISSUE THREAD

**Issue by daino3** [rails/actioncable#120]
FYI - This is a question. I'm trying to run cukes against the websocket features we've implemented and can't seem to figure out where to start debugging, or if this is even supported right now.

I've tried the cukes running with actioncable running as a standalone service as well as middleware of the main application like described in the README. Basically, the cukes assert against a live update rendering on the screen, but there are no updates. 

Rails - 4.2.4
ruby - 2.2.2
redis_version:2.6.7
phantomjs - 1.9.8

Capybara server_port 31337

Procfile
```
# using foreman to manage in different environments
action_cable: bundle exec puma -p 28080 cable/config.ru
```
Javascript consumer
```coffeescript
  createSubscription = ->
    $scope.cable = Cable.createConsumer("ws://0.0.0.0:28080")
    $scope.cable.subscriptions.create('MessagesChannel', {
    ...
```
Allowing request origins to include capybara server port
```ruby
# Config/initializers/actioncable.rb
ActionCable.server.config.allowed_request_origins = "http://localhost:31337"
```

So first, I run: `foreman start` to get the backing services up and running, including actioncable running on 28080. And then, I run the cucumber suite.

When I tail the test logs I see: 
```
[ActionCable] Broadcasting to market_data:{:book...}
```

However, the actioncable log running at 28080 is silent... leading me to believe that when the test rails app broadcasts to the actioncable service, something isn't configured correctly. 

Everything works in development and our demo environment. It seems to only be cucumber specs that we can't get to live update. 

Please let me know if you need anything else.

**Comment by dhh** [comment]
Not sure what the problem is, but please use http://stackoverflow.com/questions/tagged/ruby-on-rails to request assistance. We're using the issue tracker just for bugs. Thanks!
