### ISSUE TITLE
Public live chat implementation between guests and connected users

### ISSUE THREAD

**Issue by devmarwen** [rails/actioncable#123]
### I'm trying to build a public live chat, here's what it's like:
A random user visits the site ( and gets a random token stored in the cookies ), when he requests a live chat session a `guest` record gets created and the chat may begin between him and an end user from the admin area. The "chat" is just a simple `conversation` that has many `messages` from the `guest` and the `user` or `current_user`.

**I'm really confused by how to connect the `guest` with the connected user from the other side :confused:**

Should I use two `connection` classes, one for the `guest` and the other for `current_user` (connected user). Or just treat the `guest` as if he was a normal `user`.

Could someone guide me or give me a big picture on how to successfully get this working. :smiley_cat:

**Comment by kayakyakr** [comment]
I don't believe that multiple connection types is fully supported at this time, you would need to be able to determine if it's a guest session or a user session in the single connection. You could create a separate channel for each, but if you're already emulating a user object for guests, you might as well just use the same channel.

**Comment by dhh** [comment]
I don't really understand the question. Maybe kayak's answer helped? But in any case, the issue tracker here is for reporting bugs, so closing this one.
