### ISSUE TITLE
Adding regexps as an option inside allowed_request_origins

### ISSUE THREAD

**Issue by adamliesko** [rails/actioncable#129]
Hey all,

at one of our projects we needed to have a greater control over the allowed request origins and didn't really wanna bother with rack-cors etc. solutions, so we had changed the implementation to also accept an Regexp as an item inside the `allowed_request_origins` array. I believe that this is something which might worthy of being as a default feature.

What do you think?

Be aware that this is my first public rails/ruby core commit and PR  https://github.com/rails/actioncable/pull/130 and any feedback is greatly appreciated. Thanks!

**Comment by dhh** [comment]
Discussion continued in #130.
