### ISSUE TITLE
Protect against Cross-Site WebSocket Hijacking using the CRSF token

### ISSUE THREAD

**Issue by dhh** [rails/actioncable#13]
WebSocket upgrade requests are susceptible to Cross-Site WebSocket Hijacking as detailed in https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html. We need to use a similar CRSF token strategy as we do to protect the rest of a Rails application against a CRSF attack. Most likely, we can probably even use the same token, or a derivative thereof. But protect we must!

**Comment by cristianbica** [comment]
I will give it a try

**Comment by uu59** [comment]
CSRF token-like protection isn't needed I think.
Just verify request header's `Origin` field or common CORS protection using `Access-Control-Allow-Origin` by response header, they protect a user as well.
Browser always set `Origin` to request header when `new WebSocket("ws://example.com")` for negotiate the protocol.

Of course CSRF token-like mechanism works too, but using CORS headers approach is simpler than that.

**Comment by gregmolnar** [comment]
@uu59 any HTTP header can be spoofed so I think a CSRF token would be a more secure solution.

**Comment by jeremy** [comment]
You can't spoof the `Origin` header in browsers. Whitelisting `Origin` is a great (and much simpler) technique to prevent CSRF.

**Comment by gregmolnar** [comment]
That's true, at least as longs as there is no SOP bypass vulnerability in the browser(which is rare).

**Comment by cristianbica** [comment]
I'm in progress with the CSRF implementation. An `Origin` based implementation would be much simpler.  I'm going to explore that and we'll see how it looks.

**Comment by gregmolnar** [comment]
I think simple is better and SOP should be the browsers responsibility. Thanks for your work on this @cristianbica !

**Comment by jeremy** [comment]
Origin whitelist implemented at #85, moving there!
