### ISSUE TITLE
Channel authorization

### ISSUE THREAD

**Issue by assimovt** [rails/actioncable#132]
What's the best approach to authorize channels? Let's say you have a multi-tenant application with user belonging to many companies. The example with `app/channels/application_cable/connection.rb` shows how to authenticate a user, but how about authorizing channel subscriptions? I thought of passing a parameter as demonstrated with Room example, but is that secure? Could someone subscribe to a room she does not access to? Any hints? Thanks!

**Comment by lsylvester** [comment]
You have access to the `current_user` inside the channel, so you should use it to verify that the user has access to the room before you start the stream.

Something like:
```ruby
class ChatChannel < ApplicationCable::Channel
  def subscribed
    stream_for current_user.accessible_rooms.find(params[:id])
  end
end
```

**Comment by assimovt** [comment]
Awesome, so no need for something like `reject_unauthorized_connection`? What about changes in permissions, say user has been removed from the room? What's the best way to handle it?

**Comment by dhh** [comment]
@assimovt You can call `ActionCable.server.remote_connections.where(current_user: user).disconnect` in the code that changes access.

**Comment by assimovt** [comment]
@dhh thanks!

**Comment by fredkelly** [comment]
Sorry to dig this back up. I'm wondering how to implement a client-side subscription using the `stream_for` method above? I want to ensure users can only subscribe to messages relating to entities owned by them.

**Comment by lsylvester** [comment]
@fredkelly You need to pass in the id when you create the subscription to get the `params[:id]` available in the `subscribed` method. Something like:

```coffeescript
App.cable.subscriptions.create { channel: "ChatChannel", id: "1" },
  ...
```
