### ISSUE TITLE
Redis Configuration from  Environment Variable

### ISSUE THREAD

**Issue by vovimayhem** [rails/actioncable#134]
I think it would be extremely nice if ActionCable's Redis Connection could be configured by just setting an environment variable - i.e.: 'REDIS_URL=redis://somehost:6739' - in the same way ActiveRecord does with 'DATABASE_URL', whenever it doesn't find the 'config/database.yml' file...

Right now, if I dismiss/forget creating the 'config/redis/cable.yml' file, ActionCable raises an error.

**Comment by kayakyakr** [comment]
just create the file and set the cable.yml to be the environment variable?

**Comment by dhh** [comment]
We're going to ship Action Cable with Rails directly, so this file will be present. I don't think this is a good fit because you may well have many Redis instances.

**Comment by vovimayhem** [comment]
Fair enough :)

@kayakyakr I ended up setting the file [like this](https://github.com/vovimayhem/rails-docker-demo/blob/feature/forum-functionality/config/redis/cable.yml).

Actually thats similar to [how I got it a couple months ago](https://github.com/vovimayhem/actioncable-examples/blob/f5e/docker-compose/config/redis/cable.yml)... but I forgot that yesterday.
