### ISSUE TITLE
Feedback about the README documentation

### ISSUE THREAD

**Issue by rosenfeld** [rails/actioncable#21]
Sorry if this is not the proper place to give you some feedback but I didn't see any indication in the README on how one should provide feedback, so I'm trying through Github issues.

We don't use any YAML's in our deploy process. We have several environments running in the same server and we achieve that by always running the production environment and generating a single config/settings.rb file with all settings, including the Redis path. So I think it would be good if you could provide an example in README about how to configure Redis without using a YAML file.

I took a quick glance at the Configuration class and it seems it's only designed to work with a YAML file. May I submit a pull request to make this a bit more flexible, while keeping the default of loading the YAML file?

Also, with regards to the documention, it wasn't clear to me what `identified_by` does exactly. Also, you mention it's possible to find all connections for a given user but I missed an example on how that would work. Such example would be very useful.

It would be also awesome, although I understand if this is outside the scope of the README, to see how this could be integrated with Devise. For example, I think the connection should be closed when the session expires according to Devise's timeout's and remember-me settings.

Overall I liked the API.

Congrats and thanks!

**Comment by dhh** [comment]
Be happy to take a fully injected Redis instance for both the broadcaster
and for the general pubsub.

I'll add an example around identified_by. It's indeed for finding
connections again later.

I don't use Devise, so someone else can take a look at that.

**Comment by rosenfeld** [comment]
> Be happy to take a fully injected Redis instance for both the broadcaster
and for the general pubsub.

I'm not sure what exactly you mean by this. I was thinking about adding an `attr_writer :redis` to ActionCable::Server::Configuration. This is not really a Redis connection instance, but simply the Redis configuration hash.

I'm not even sure why we need provide a hash since it seems you expect and use only the :url part:

https://github.com/rails/actioncable/blob/master/lib/action_cable/server/base.rb#L49

I'm also worried about thread safety. I'm not really sure how EventMachine works and whether there's a possibility for it to handle multiple threads. For example, Puma would start a new thread for each new connection I guess. But I don't know if EventMachine would process all requests in a single thread and then reply to the original thread somehow.

If there is the possibility for ActionCable to run this code from different threads, then there are some thread safety issues in parts of the implementation:

https://github.com/rails/actioncable/blob/master/lib/action_cable/server/base.rb#L21

For example, an instance of this is not thread-safe:

https://github.com/rails/actioncable/blob/master/lib/action_cable/server/connections.rb

Also, I'm not sure if an instance of the server is supposed to be used by multiple threads concurrently. If so, looking at em-hiredis I couldn't see any statements in the README on whether an instance of a pubsub call would be thread-safe or not.

https://github.com/mloughran/em-hiredis

Anyway, may I simple add an `attr_writer :redis` to Server::Configuration?

**Comment by gregmolnar** [comment]
@rosenfeld I just wrote a blogpost about how I made devise and actioncable work together: http://www.rubytutorial.io/actioncable-devise-authentication/

**Comment by rosenfeld** [comment]
Thanks, @gregmolnar :)

**Comment by dhh** [comment]
Would be great to have that Device tutorial as part of a guide explaining AC. Please do PR that.

**Comment by gregmolnar** [comment]
@dhh do you mean to add it as a section to the readme?

**Comment by dhh** [comment]
We can start with that. Actually, we can just do a link to that article even.
