### ISSUE TITLE
Application Base Class Names RFC

### ISSUE THREAD

**Issue by lsylvester** [rails/actioncable#27]
It is currently recommended that users create a `ApplicationCable::Channel` class in `app/channels` and it is required that users create a `ApplicationCable::Connection` which is recommended to also be in `app/channels`

I think that it would be nicer to not have to namespace the base classes under `ApplicationCable`.

Instead, I think that it would be better to use a base channel class name `ApplicationChannel` and to rename the `Connection` to  `Cable` as I don't think that there is any real difference between a connection and a cable and that it makes more sense to put application logic in a cable instead of a connection, and then have a `ApplicationCable` class that sits in `app/cables`.

I would be happy to make a PR for this if anyone thinks it is a good idea.

**Comment by dhh** [comment]
That's what we had originally. I think calling one of the elements "cable"
when the whole package of the feature is "cable" is confusing. I don't
think this is going to be of any practical concern as when Action Cable is
baked, we'll ship it in Rails 5 with all these stubs automatically
generated.
