### ISSUE TITLE
Inconsistent version numbers

### ISSUE THREAD

**Issue by maclover7** [rails/actioncable#40]
The [gemspec](https://github.com/rails/actioncable/blob/master/actioncable.gemspec#L3) lists that the current ActionCable version is 0.1.0. However, [action_cable.rb](https://github.com/rails/actioncable/blob/master/lib/action_cable.rb#L21) lists that the current ActionCable version is 0.0.3.

There should be one standardized place to record the version number, to avoid confusion.

**Comment by matthewd** [comment]
Fixed by #41
