### ISSUE TITLE
Few questions and concerns about ActionCable

### ISSUE THREAD

**Issue by nateless** [rails/actioncable#44]
Hello guys,

First of all I'm really happy to see this in Rails. Thanks @dhh and all the rest! I'm already thinking to test it and port our mess to ActionCable however I have few questions I want to address first as our application is heavy-loaded ( we use tubesock with puma ), have around 500 clients online and each of them gets up to 200-300 messages per second, also we deal with finance and thus its very important to make it safe.

1. How many connection to database will use one consumer subscribed let's say to 10 subscriptions? (if I understand correctly AC uses threads for each subscription, right?) 

2. Has anyone experienced leaked mysql connection in case client was disconnected with network error or some exception? 

3. What about synchronization? AC allows many connections being open by one user, it creates a possibility for race condition. Let's assume we do some work after connection. User can create hundreds of parallel requests and we get into race condition. This also links to 1st question, if each subscription works in separate thread, how data is being synchronized? For example we have changed user balance in `TransferChannel`, will those changes be local to that thread? Does `current_user.with_lock`  thread safe?

4. Currently to block race-condition attacks we use `Mutex`, do you plan to add something like exclusive access?

5. Last change in tubesock was very disappointed as of now if consumer gets an exception on server it just being silently ignored (they don't even log that error), what's your plan on dealing with exceptions on client and server and ability to auto-reconnect?

Sorry if my question may sound as I'm too lazy to check it by myself. However it will require huge amount of time and public tests to check everything.

Regards,
Nate

**Comment by dhh** [comment]
Hey, hey.

A few quick answers:

1. It's one database connection per cable connection, not per channel subscription. So 500 clients online = 500 database connections.
2. There's heartbeat monitoring. If the client doesn't respond, we can disconnect.
3-4. No plans to do any synchronization protection in the framework. We'll leave that as an app concern.
5. Client-side will automatically try to reconnect if the connection is cut (as it would be on exception). We also log the exception.

**Comment by lsylvester** [comment]
@dhh - Can I clarify the first answer? I thought that the database connection was not maintained for each channel, but was checked out of the pool each time it did some work (like set up a connection or run an action) and then checked back into the pool. So the number of require database connections is determined by the worker pool size and not number of clients online. 

I think the number of connections that match the number of cables is websocket connections, not database connections.

**Comment by dhh** [comment]
Yes, that's right. My mistake.

**Comment by gauravtiwari** [comment]
@nateless @dhh @lsylvester Have you seen this - [Centrifugo](https://github.com/centrifugal/centrifugo) and [Centrifuge-ruby](https://github.com/centrifugal/centrifuge-ruby)? 

This looks very similar to the approach actioncable is taking - (using Redis PUB/SUB), but the framework is far more reliable and scalable as it uses GO/Redis replication.  Also, it's plug and play.

**Comment by kaspth** [comment]
@gauravtiwari Action Cable primary purpose isn't to be the fastest solution around. It's extending the reach of your lovely Active Record domain model, so you don't have to rewrite it in other environments.

Can those libraries help us do that?

I'm closing this as the original issue has been resolved by @dhh and @lsylvester's answers.

**Comment by gauravtiwari** [comment]
Sorry @kaspth if my comment was too vague. I saw David's presentation on ActionCable. I was too very excited in the beginning. I agree and see the importance of integrated systems, which David outlined in his presentation, however, for real-time I don't quite understand about reinventing the wheel when a lot of other tested solutions are out there. 

To me, real-time means message delivery between connected clients and if we can do that with other systems that more tested and primarily made just to do that I am not sure if there is a need to reinvent this for rails. I actually tried integrating ActionCable into existing rails 4.2.3 app and the steps involved to do so were more than the steps involved in integrating paid platforms like Pusher or Open source ones like - Centrifugo or Faye Websockets. Both are actually framework independent. 

From a software perspective, real-time is standalone functionality on its own with its own challenges and I just felt that this is being redone here plus this puts future maintainability etc.  Maybe this effort can be focussed on more non-trivial things. 

Sorry, if I am missing something here.

**Comment by dhh** [comment]
Use whatever floats your boat, Gaurav. I'm using Action Cable on a project
and love having it be an integrated part of the system, not some
"standalone functionality". Just like everything else in Rails is part of
an integrated system.

I'm also not sure what this discussion would even hope to achieve? Were you
actually thinking that someone would read your comments and think "oh,
yeah, actually, we shouldn't work on Action Cable because there's another
piece of software written in Go that also deals with websockets".

If you're simply trying to reason through, on your own, whether Action
Cable is right for you, that's fine. But I don't think the Rails issue
tracker is the place for such a personal quest. Best of luck with it,
though.
