### ISSUE TITLE
Not quite an issue, more of a n00b issue.

### ISSUE THREAD

**Issue by jalexy12** [rails/actioncable#53]
I was setting up action cable earlier in one of my projects to experiment, and it just wasn't working. I wasn't receiving data client side and it appeared as if my "CommentsChannel" wasn't even being instantiated. I have a very similar setup as the demo, and was following along with this tutorial: http://blog.bigbinary.com/2015/07/19/using-reactjs-with-rails-actioncable.html

According to the logs, I was getting this: runtimeError - Unable to find subscription with identifier: {"channel":"Comments Channel"}

I thought I had copied everything over from the tutorial. I restarted all of my servers(redis, cable server, rails server), ran ./bin/setup and everything magically worked. Am I missing something in the ./bin/setup executable that makes this all come together? 

Thanks for the hard work, and sorry for the goofy question. If it's something I can add to the README for setup outside of the example, I can do that as well.

**Comment by javan** [comment]
Are you specifying `Comments Channel` somewhere instead of `CommentsChannel`?

**Comment by jalexy12** [comment]
I wasn't which interested me in the logs, I think it had to do more with copy and pasting as opposed to anything else, because it appeared as CommentsChannel in the logs.
