### ISSUE TITLE
Heartbeat improvement

### ISSUE THREAD

**Issue by leckylao** [rails/actioncable#55]
Hi @dhh,

From the server side, there's heartbeat sending from the server to all clients every 3 seconds. And I think this is a bit excessive and it may cause performance issue when dealing with finance or heavy load on the WebSocket.

From the client side, connection_monitor is sending the subscribe message every 4-8 seconds, this would increase the server load especially when all of the clients sending the subscribe message at the same time.

The heartbeat and connection_monitor are similar to reintroduce the asynchronous notification polling which WebSocket try to resolve. I reckon it could be improved by using socket.onclose event and socket.readyState for the reconnection instead of checking the stale connection.

```javascript
socket.onclose = function() {
    consumer.connection.reopen() if socket.readyState === 3;
}
```

**Comment by javan** [comment]
> connection_monitor is sending the subscribe message every 4-8 seconds

Because your users change pages every 4-8 seconds?

**Comment by dhh** [comment]
We've found that those callbacks were not reliable across all situations
and browsers. The only reliable method we've found has been using a
heartbeat.

How is a heartbeat every 3s per connection a performance problem in your
case?

**Comment by leckylao** [comment]
Hi @javan,

not sure whether it's a bug or not. But if you 

1. Clone the actioncable-exmaple and https://github.com/leckylao/em-websocket-example
2. Change actioncable-example/app/assets/javascripts/channels/index.coffee to point to ws://localhost:3001
3. Run actioncable-example/ rails s as client and run em-websocket-example/ ruby app.rb as server

Then you will see "Received: {"command":"subscribe","identifier":"{\"channel\":\"CommentsChannel\"}"}" every 4-8 seconds, which I think it's due to connection_monitor that reopening the connection.

**Comment by leckylao** [comment]
Thanks @dhh for the explanation.

> How is a heartbeat every 3s per connection a performance problem in your case?

Some metrics I found:
* https://mrotaru.wordpress.com/2013/06/20/12-million-concurrent-connections-with-migratorydata-websocket-server/ 
> In this benchmark scenario, MigratoryData scales up to 12 million concurrent users from a single Dell PowerEdge R610 server while pushing up to 1.015 Gbps live data (each user receives a 512-byte message every minute).
Result in 12m, Average latency 268 milliseconds, Maximum latency 2024 milliseconds, Network Utilization 1.015 Gbps. 

* http://colobu.com/2015/05/22/implement-C1000K-servers-by-spray-netty-undertow-and-node-js/ Sorry about it's in Chinese, opens in Chrome should translate it.
> Netty Server - To all 1.2 million per minute websocket send a message, the message content for the current time server. Send display single-threaded send, the server sends finished about 1.2 million total time 15 seconds.
> Spray Server - To all 1.2 million per minute websocket send a message, the message content for the current time server. High CPU usage, send quickly, bandwidth of up to 46M. After a mass takes about 8 seconds.
> Undertow - To all 1.2 million per minute websocket send a message, the message content for the current time server. Mass takes about 15 seconds to play again.

Heartbeat would create similar load to the server and the bandwidth, which I think it would cause a performance issue on large concurrent connections.

**Comment by dhh** [comment]
I think you're going to be disappointed if you actually try to do any Ruby
work in these channels and expect that level of performance :). The
heartbeat is just a single piece of text data that requires nothing to
generate. Actual apps will be doing actual things in these channels that
are far slower than what a heartbeat overhead will be.

In any case, I haven't found it to be optional. If you can't reliably tell
when the connection has been cut, then the app might be fast, but it won't
work well.

**Comment by leckylao** [comment]
> I think you're going to be disappointed if you actually try to do any Ruby
work in these channels and expect that level of performance :)

Nah, those just some metrics I found that can better show the impact. Another thought, I don't think they implements something like heartbeat but can still achieve stability on that level :blush:

> The heartbeat is just a single piece of text data that requires nothing to
generate. Actual apps will be doing actual things in these channels that
are far slower than what a heartbeat overhead will be.

Most of the case WebSocket are being use as notification which only happens when it occurs. In this case, I think heartbeat is generating more traffics than the actual jobs.

> In any case, I haven't found it to be optional. If you can't reliably tell
when the connection has been cut, then the app might be fast, but it won't
work well.

In this case, how about moving heartbeat and connection_monitor into an optional configuration. So that it doesn't enable by default. If people facing trouble with the connection then they can enable it.

**Comment by dhh** [comment]
Optimizing for correctness out the box over peak performance seems like a better trade-off to me. If someone actually hits a point in a real application where heartbeat traffic proves to be an issue, we can consider offering a way to turn off heartbeats. Thanks for your consideration and I look forward to hearing about your Action Cable deployment!

**Comment by leckylao** [comment]
> We've found that those callbacks were not reliable across all situations and browsers

In order to further understand the issue, could you provide an example/demo or explain more about the issue please? How is it not reliable? Thank you. 

http://caniuse.com/#search=websocket shows WebScoket is now 87.23% support that maybe the issue should be and has been resolved natively.

**Comment by dhh** [comment]
This was in testing across a variety of browsers, restore situations, and
mobile scenarios. Don't have a test suite available for reproduction. Would
be nice to have, but it's unlikely that we're going to invest any time into
this, given that we have a working solution. All this testing was done in
the last 3-4 months, though. Feel free to work on such a suite if you'd
like to advance this.
