### ISSUE TITLE
override websocket events on the client

### ISSUE THREAD

**Issue by sebyx07** [rails/actioncable#56]
is there a way to handle error/close ? i tried to use 

myCableConsumer.connection.webSocket.onclose = function(){..}

and webSocket.onclose will always be null;

**Comment by javan** [comment]
I don't recommend reaching into connection's `webSocket` like that. It gets [reassigned when the connection is reopened](https://github.com/rails/actioncable/blob/master/lib/assets/javascripts/cable/connection.js.coffee#L15) so your `onclose` handler will be lost. Instead, add a `disconnected` callback to your subscriptions, which will be called when the connection is closed and on error:

```coffee
cable = Cable.createConsumer "ws://cable.example.com"

cable.subscriptions.create "ExampleChannel",
  disconnected: ->
    ...
```
