### ISSUE TITLE
Identifiers that don't implement to_global_id

### ISSUE THREAD

**Issue by mrlhumphreys** [rails/actioncable#63]
Hi everyone,

I was working on replacing polling with `ActionCable` in an app. It's been good so far and things are working mostly as expected. Thanks everyone who worked on this. I've been anticipating this kind of feature for a long time.

I ran into a small issue when using a uuid string as the identifier for a connection. (The scenario is that this uuid string is a unique identifier for a session and the user is not logged in, so current_user is nil)

An error was raised in lib/connection/identification.rb#connection_gid saying:

```
undefined method `to_global_id' for "121cce49-3f9a-4871-904f-5b6d0e0f5d25":String
```

So, it seems like there's a requirement that the identifier should be something that implements `to_global_id`. Currently, I'm working around it by using a hand-rolled class that implements `to_global_id`.

My question is, should the identifier be able to handle objects that don't implement `to_global_id`?

If so, then this leads to the next question on how a particular object can be converted to a string to be used as the `connection_identifier`. `to_global_id` is fine for `ActiveRecord` models. But, for other kinds of objects, I'm not sure.

Any thoughts?

**Comment by dhh** [comment]
Yeah, we should probably just try(:to_global_id) and then do try(:to_s) if that doesn't work 👍

**Comment by mrlhumphreys** [comment]
Thanks. That sounds good. I'll work on implementing that.

**Comment by kaspth** [comment]
Fixed by https://github.com/rails/actioncable/pull/65
