### ISSUE TITLE
can not obtain cookies.signed[:user_id] in Connection class 

### ISSUE THREAD

**Issue by zcpdog** [rails/actioncable#66]
I am using rails 4.2 ruby 2.2.1 with actioncable master branch,
I followed the steps on README.md to identify user,  my connection.rb is like 

```ruby
#app/channels/application_cable/connection.rb 
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user
   
    def connect
      p "======================"
      p cookies.signed[:user_id]
      p "======================"
      self.current_user = find_verified_user
    end

    protected
      def find_verified_user
        if current_user = User.find(cookies.signed[:user_id])
          current_user
        else
          reject_unauthorized_connection
        end
      end
  end
end
```

My system is using devise to handle authentication, I put 

```ruby
#app/controllers/application_controller
cookies.signed[:user_id] = current_user.id if current_user.present?
```

After login, I found I am able to get cookies.signed[:user_id] from normal requests, but the websocket connect can not get the cookies.signed[:user_id]

```ruby
#out put from puma -> bin/cable
127.0.0.1 - - [21/Aug/2015 19:10:20] "GET / HTTP/1.1" HIJACKED -1 0.0007
"======================"
"======================"
```

Can I use current actioncable with rails4 or it is rails5 only?  
Or is this a bug in rails4? 

Thanks

**Comment by kaichen** [comment]
Do you launch your actionable server and rails web server under same domain? It may causes by CORS issue.

If you run on you local dev machine, please unify `127.0.0.1` or `localhost` address.

**Comment by zcpdog** [comment]
Hi Kai, 
As you said, I mixed 127.0.0.1 and localhost, the rails app server was running on localhost

After I switched to 127.0.0.1 everything just works. 

Thank you and all the actioncable contributors 

I think we can close this issue

**Comment by ajahongir** [comment]
@kaichen :+1:
