### ISSUE TITLE
Management of client (JS-side) configuration for WS server

### ISSUE THREAD

**Issue by dgsan** [rails/actioncable#72]
So in your JS "client" you have to call something like `Cable.createConsumer('ws://example.com:12345')` to create your App.cable. But in development you probably want to call something like `Cable.createConsumer('ws://127.0.0.1:12345')` instead. Not sure how it'd work, but maybe there needs to be some configuration management for the JS side of things? 

The only idea I have is a .yml or .json file somewhere that causes the js asset pipeline to create/include some sort of `App.settings` or `Rails.settings` object of config key/vals based on the current environment so that you can just call something like `Cable.createConsumer(App.settings.websocket_host)` and have it be the right host for the env.

Anyway, just some thoughts. There are probably other approaches that make sense.

**Comment by smellsblue** [comment]
Here's what I've been doing so far... in my layout in the head, I add a section with a meta tag:
```
<% if Rails.env.production? %>
  <meta name="websocket-url" content="wss://example.com:12345" />
<% else %>
  <meta name="websocket-url" content="ws://localhost:12345" />
<% end %>
```

Then, in my CoffeeScript, I connect like so:
```
App.cable = Cable.createConsumer $("meta[name='websocket-url']").attr("content")
```

You could pretty easily move the content for the meta tag into your environment.rb, then have just 1 meta tag which grabs the config value.

I found something like this absolutely necessary, as in development I am using "ws" versus production I am using "wss" (otherwise I get errors due to it not being SSL).

**Comment by dgsan** [comment]
Yeah, I'm doing something similar, looked into using Gon, but ultimately decided to just put my own script tag in the header of a special layout for pages that use ActionCable. It just seems like there ought to be a convention that matches other Rails conventions.

**Comment by kayakyakr** [comment]
``Cable.createConsumer('ws://' + window.location.hostname + ':12345')`` would work if you're just using port.

My implementation will use ``Cable.createConsumer('ws://' + window.location.host + '/websocket')``

**Comment by dhh** [comment]
Continuing the discussion in the PR.
