### ISSUE TITLE
Redis subscribed race condition

### ISSUE THREAD

**Issue by smellsblue** [rails/actioncable#74]
I have a post action which in turn notifies a thread I have running to stop its processing. When the processing is complete, this in turn triggers some broadcast messages to tell the browser to update the view with some new details. The thread doesn't die right away, so after the redirect from the post, the old state will be visible until the ActionCable broadcast message comes in.

Unfortunately, I am hitting a race condition... the browser reloads from the redirect, but then never gets the message with the new state. At first I thought this might be a race condition from between when the browser first loads to when the ActionCable websocket is actually connected. So, I listened for the consumer to be connected and pulled the state via a JSON request... thus I should (for sure) get the correct state after the redirect from the post:

```coffee
App.myChannel = App.cable.subscriptions.create "MyChannel",
  connected: ->
    # ... call JSON request and update state

  received: (data) ->
    # ... update state
```

This didn't solve the problem. So I dug a bit more and found that my redis subscription wasn't successfully subscribed until after my websocket was connected, and that was the race condition. I have a pull request that I will link to this issue which demonstrates a possible fix such that the following would solve my race condition:

```coffee
App.myChannel = App.cable.subscriptions.create "MyChannel",
  subscribed: ->
    # ... call JSON request and update state

  received: (data) ->
    # ... update state
```

I realize my solution is a bit hacky and probably not the ultimate desired solution, but I would love to dig in and help with the final solution. Where would be the best place to discuss how this should actually be solved?

**Comment by dhh** [comment]
We've seen the same issue. @lifo did you have a take on what we needed to do to solve this?

**Comment by smellsblue** [comment]
@lifo I've been thinking about this problem a bit, and I feel like keeping just the "connected" event would be ideal... It keeps the API simpler. With that, 2 solutions come to my mind:
* Delay the websocket response from the ActionCable server until Redis has responded, so the JavaScript doesn't have to change
* Send a special message to the client once Redis has responded, delaying the "connected" event until this is seen

Do you think either of these might work?

**Comment by kroehre** [comment]
@lifo I've also run in to this issue. Sometimes a background process completes quickly and broadcasts before the browser has connected. I've overcome this by using an intermediate object that is persisted in Redis for a short while when the process completes. It broadcasts immediately, which works when the browser has already connected. In my channel, when a subscription is started, I look up the intermediate object to see if there's a message and transmit it if so. This covers the case when the browser wasn't subscribed when the process finished.

**Comment by javan** [comment]
I believe https://github.com/rails/actioncable/pull/98 resolved this issue. `connected` is now called when the subscription is active on the server, not when the WebSocket first connects.
