### ISSUE TITLE
Continuous Connection Monitor activity when disconnected

### ISSUE THREAD

**Issue by vanboom** [rails/actioncable#76]
connection_monitor.coffee
```javascript
 disconnected: ->
    if @reconnectAttempts++ is 0
      setTimeout =>
        @consumer.connection.open() unless @consumer.connection.isOpen()
      , 200
```
When my user logs out and we expire the user cookie, this code is continuously retrying.  This is evident by the cable task printing continuously...
  127.0.0.1 - - [14/Sep/2015 21:34:01] "GET / HTTP/1.1" HIJACKED -1 0.0010

When a user logs in, the continuous print stops.   This is causing CPU usage in the browser and server... how do we get it to stop when we are disconnected? 

thanks!

**Comment by dhh** [comment]
See answer in #81.
