### ISSUE TITLE
 Deploying under SSL

### ISSUE THREAD

**Issue by vanboom** [rails/actioncable#79]
I have an actioncable app working great on my development machine, and am trying to deploy it to a secure production server. 

``` javascript
App.cable = Cable.createConsumer(ws://[ip_address]:28080)
```
which results in...
```
2015-09-17 01:11:06 -0400: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2015-09-17 01:11:06 -0400: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.13.4", "GATEWAY_INTERFACE"=>"CGI/1.2"}
```

Could you offer some guidance on how to deploy ActionCable under https/wss?    Thanks!

**Comment by marcinruszkiewicz** [comment]
This is pretty obvious and might be just a github comments or copy/pasting thing, but still. ;)

a) address should be "wss://..."
b) it should be enclosed in "" or ''

**Comment by vanboom** [comment]
I am actually passing the websocket address using the gon gem.  Here is what the javascript looks like in my rendered page where [ipaddress] is a real IP address: 
    gon.websocket="wss://[ipaddress]:28080";
    App.cable = Cable.createConsumer(gon.websocket);

**Comment by marcinruszkiewicz** [comment]
Sorry for doubting you, it's just so easy to forget about this stuff, so it's reasonable to point at it first ;)

I didn't have this problem myself, but with my heroku deployment I'm starting the actioncable server a bit differently (as a middleware rather than a separate process) than it's described here in the readme. 

Your problem seems to be something similar to the one in https://github.com/puma/puma/issues/27 so you might try the solution in the last post there.

**Comment by vanboom** [comment]
No worries, thanks for helping.  I am a newb w/r to web sockets, so I appreciate your help.  ActionCable is working beautifully on my localhost -- a GREAT addition to Rails imho!

I wonder if there is a key/cert pair that I need to give the ActionCable server.  

I am deploying on a DigitalOcean slice, Ubuntu.

**Comment by vanboom** [comment]
This appears to be the appropriate solution...specify the address with ssl:// instead of tcp://

e.g.
bundle exec puma config.ru -b 'tcp://0.0.0.0:3456?key=/path/to/key.key&cert=/path/to/cert.crt'
instead of
bundle exec puma config.ru -b 'ssl://0.0.0.0:3456?key=/path/to/key.key&cert=/path/to/cert.crt'

However, this leads to
2015-09-17 11:27:20 -0400: Rack app error: #<TypeError: no implicit conversion of Puma::MiniSSL::Socket into Integer>
/rails_apps/helphub/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:762:in `attach_fd'

...coming from the cable server

**Comment by marcinruszkiewicz** [comment]
Might be easier to just go the middleware way as described here: http://www.thegreatcodeadventure.com/deploying-action-cable-to-heroku/ (minus the heroku parts, obviously).

**Comment by vanboom** [comment]
Thanks...I tried using the middleware way this morning.  When ActionCable tries to connect, I am seeing an error `failed: Invalid frame header` when the WebSocket tries to connect.  I have confirmed the middleware is routing to ActionCable.   When the connection fails, ActionCable continuously retries to connect.

```javascript
    Connection.prototype.open = function() {
      if (this.isOpen()) {
        throw new Error("Must close existing connection before opening");
      } else {
-->        this.webSocket = new WebSocket(this.consumer.url);
        return this.installEventHandlers();
      }
    };
```

**Comment by vanboom** [comment]
https://github.com/phusion/passenger/issues/1202#issuecomment-141675220

WebSockets do not work under Apache/mod_passenger.  I converted my hosting over to NGINX, and the app works perfectly.
