### ISSUE TITLE
Close/Disconnect Consumer

### ISSUE THREAD

**Issue by kroehre** [rails/actioncable#81]
I may be missing something, but I can't seem to get a consumer to stop reconnecting when its connection is closed. Calling `cable.connection.close()` closes the connection, but a new connection is made and heartbeats continue. Any ideas?

**Comment by kroehre** [comment]
I'm able to successfully disconnect the cable doing something similar to this:

```
var cable = Cable.createConsumer(connectionUrl);
var subscription = cable.subscriptions.create(channel, { received: function(data) { ... } });
subscription.unsubscribe();
cable.connectionMonitor.stop();
cable.subscriptions.subscriptions = [];
cable.connection.close();
cable = null;
```
It's pretty intrusive to the internals of ActionCable. The key part here is:
```
cable.subscriptions.subscriptions = []
```
Without that, the connectionMonitor will be notified via its subscription when the websocket disconnects. When that happens the connectionMonitor restarts itself (even though it was stopped), and re-establishes the websocket connection.

**Comment by kroehre** [comment]
This may be related to #76

**Comment by dhh** [comment]
Yeah, I think we need a separate message type that basically says "close this connection and don't try again". If you'd like to work on that, please open a PR.
