### ISSUE TITLE
Uniq connection identifier

### ISSUE THREAD

**Issue by nateless** [rails/actioncable#86]
Hello guys, 

I've been playing with AC and got stuck with small problem. Let's assume I want to make something as on Github when you open site from another tab and first one gets an alert and disconnects from WS.

If I put this code into `Connection#connect` class, both tabs will start disconnect each other:

```ruby
ActionCable.server.remote_connections.where(current_user: current_user).disconnect
```

Is there any way to exclude current connection from the list? Because `disconnect` will broadcast to `internal_redis_channel`.

**Comment by danielschwartz** [comment]
FYI -- I've opened #88 which proposes an exclusion API for ActionCable.server and adds current_connection as a unique connection identifier

**Comment by dhh** [comment]
@nateless If you want to disambiguate like that, I think you're going to have to pass something like a connection token. I'd be happy to see us do something like where(current_user: x).where.not(token: y). Please open a PR if you want to pursue that!
