### ISSUE TITLE
Views or Data over the wire?

### ISSUE THREAD

**Issue by jrguenther** [rails/actioncable#87]
If I remember dhh's keynote correctly, one of the examples seemed to show how to send a JS view. I've read through the source and the example source and I can't find an example of how to do it. The readme only show `received: ->(data)`. Is there any documentation about how to send JS views over the wire?

**Comment by dhh** [comment]
You send JSON. That JSON can include values that are full HTML templates.

**Comment by jrguenther** [comment]
Ah, ok. I see now. Once the data is received whether plain data or HTML as data, you handle the DOM update in `received`.

**Comment by kaspth** [comment]
:grin:
