### ISSUE TITLE
Add ability to exclude specific connection from broadcast

### ISSUE THREAD

**Issue by danielschwartz** [rails/actioncable#88]
If you use a connection to perform an action that causes a broadcast you will always have to exclude yourself from reperforming the action client side. This feels like a pretty core use case, and feels like something that should be a first class citizen within ActionCable.

For reference this is how Pusher does this: https://pusher.com/docs/server_api_guide/server_excluding_recipients

The idea would be something like this:

```rb
class ChatChannel < ApplicationCable::Channel
    def subscribed
        @id = some_unique_connection_id
        stream_from "chat"
    end

    def send_message(data)
        ActionCable.server.broadcast("chat", data, exclude: @id)
    end
end
```

Where `exclude` would allow you to tell ActionCable to broadcast the message out to everyone except the connection given.

Ideally `@id` would actually be set by `ActionCable::Channel` and you could simply use it as something like `current_connection`

**Comment by dhh** [comment]
That use case makes sense. I think we can make it smarter, though. Basically, tag broadcast messages with an internal identifier for the connection, and then have something like `stream_from "chat", exclude_own_messages: true`.

If you want to work on that, please open a PR!
