### ISSUE TITLE
Lack of Generators

### ISSUE THREAD

**Issue by TheAustinSeven** [rails/actioncable#92]
As of right now there are no generators for new actioncable connections. It seems that to adhere to the  "rails-y" way of things there should be at least an initializing generator that adds the code necessary to start adding connections. Is this an issue or is there a reason this hasn't been done yet?

**Comment by kaspth** [comment]
Action Cable is alpha software, so it hasn't been done yet. Here's a pull request adding channel generators to take inspiration from: https://github.com/rails/actioncable/pull/17 — in case you want to try your hand at a pull request :grin:

**Comment by TheAustinSeven** [comment]
Awesome, I'll get right on it.

**Comment by seuros** [comment]
Generators should be added after the API is stable. I will update the PR when we reach that state.
Adding generators now will just make refactoring the API more time consuming.

**Comment by TheAustinSeven** [comment]
@seuros There are still some things that should be added. I started working on one that has some aspects more similar to the generators we see with other parts of rails.

**Comment by TheAustinSeven** [comment]
The pull request I submitted is #96.
