### ISSUE TITLE
Redis-sentinel support

### ISSUE THREAD

**Issue by badlamer** [rails/actioncable#99]

**Comment by seuros** [comment]
Redis sentinels are supported by default in the redis gem.

**Comment by badlamer** [comment]
@seuros but actioncable use em-hiredis gem, which does not support sentinel connections

**Comment by seuros** [comment]
The support should be added in em-hiredis then.

**Comment by badlamer** [comment]
Need a special connection url em-hiredis - **SUBSCRIBE** since the operation can be performed in a mode readonly, it can be used for connection em-hiredis to localhost.
Meanwhile broadcating goes through the driver redis-rb, who once supported the sentinel hook up, but the url's in such a case is redis://sentinel_group - which is not compatible with the em-hiredis.

I`m solved this with monkey patch:

```ruby
module ActionCable
  module Server
    class Base
      def redis
        @redis ||= EM::Hiredis.connect(config.redis[:hiredis_url]).tap do |redis|
          redis.on(:reconnect_failed) do
            logger.info '[ActionCable] Redis reconnect failed.'
          end
        end
      end
    end
  end
end
```
But still needed a scalable solution.
